#ifndef BUILD_PROFILE_H
#define BUILD_PROFILE_H

#define HYDROPONIC_PROFILE_OPERATIONAL 0
#define HYDROPONIC_PROFILE_USB_STAGE1 1
#define HYDROPONIC_PROFILE_USB_STAGE2_MAIN_PUMP 2
#define HYDROPONIC_PROFILE_USB_STAGE3_NUTRIENT_PUMPS 3

#ifndef HYDROPONIC_BUILD_PROFILE
#define HYDROPONIC_BUILD_PROFILE HYDROPONIC_PROFILE_OPERATIONAL
#endif

#if HYDROPONIC_BUILD_PROFILE == HYDROPONIC_PROFILE_USB_STAGE1
#define HYDROPONIC_BUILD_PROFILE_NAME "USB_STAGE1"
constexpr bool ACTUATORS_LOCKED = true;
constexpr bool MQTT_PUMP_COMMANDS_ENABLED = false;
constexpr bool SERIAL_ACTUATOR_COMMANDS_ENABLED = false;
constexpr bool MAIN_PUMP_ACTUATION_ENABLED = false;
constexpr bool NUTRIENT_PUMP_ACTUATION_ENABLED = false;
constexpr bool SPARE_ACTUATION_ENABLED = false;
constexpr bool MAIN_PUMP_CONTINUOUS_ENABLED = false;
constexpr unsigned long PROFILE_MAIN_PUMP_MAX_DURATION_MS = 0;
constexpr unsigned long PROFILE_NUTRIENT_PUMP_MAX_DURATION_MS = 0;
#elif HYDROPONIC_BUILD_PROFILE == HYDROPONIC_PROFILE_USB_STAGE2_MAIN_PUMP
#define HYDROPONIC_BUILD_PROFILE_NAME "USB_STAGE2_MAIN_PUMP"
constexpr bool ACTUATORS_LOCKED = false;
constexpr bool MQTT_PUMP_COMMANDS_ENABLED = true;
constexpr bool SERIAL_ACTUATOR_COMMANDS_ENABLED = false;
constexpr bool MAIN_PUMP_ACTUATION_ENABLED = true;
constexpr bool NUTRIENT_PUMP_ACTUATION_ENABLED = false;
constexpr bool SPARE_ACTUATION_ENABLED = false;
constexpr bool MAIN_PUMP_CONTINUOUS_ENABLED = false;
constexpr unsigned long PROFILE_MAIN_PUMP_MAX_DURATION_MS = 3000;
constexpr unsigned long PROFILE_NUTRIENT_PUMP_MAX_DURATION_MS = 0;
#elif HYDROPONIC_BUILD_PROFILE == HYDROPONIC_PROFILE_USB_STAGE3_NUTRIENT_PUMPS
#define HYDROPONIC_BUILD_PROFILE_NAME "USB_STAGE3_NUTRIENT_PUMPS"
constexpr bool ACTUATORS_LOCKED = false;
constexpr bool MQTT_PUMP_COMMANDS_ENABLED = true;
constexpr bool SERIAL_ACTUATOR_COMMANDS_ENABLED = false;
constexpr bool MAIN_PUMP_ACTUATION_ENABLED = false;
constexpr bool NUTRIENT_PUMP_ACTUATION_ENABLED = true;
constexpr bool SPARE_ACTUATION_ENABLED = false;
constexpr bool MAIN_PUMP_CONTINUOUS_ENABLED = false;
constexpr unsigned long PROFILE_MAIN_PUMP_MAX_DURATION_MS = 0;
constexpr unsigned long PROFILE_NUTRIENT_PUMP_MAX_DURATION_MS = 1000;
#elif HYDROPONIC_BUILD_PROFILE == HYDROPONIC_PROFILE_OPERATIONAL
#define HYDROPONIC_BUILD_PROFILE_NAME "OPERATIONAL"
constexpr bool ACTUATORS_LOCKED = false;
constexpr bool MQTT_PUMP_COMMANDS_ENABLED = true;
constexpr bool SERIAL_ACTUATOR_COMMANDS_ENABLED = true;
constexpr bool MAIN_PUMP_ACTUATION_ENABLED = true;
constexpr bool NUTRIENT_PUMP_ACTUATION_ENABLED = true;
constexpr bool SPARE_ACTUATION_ENABLED = true;
constexpr bool MAIN_PUMP_CONTINUOUS_ENABLED = true;
constexpr unsigned long PROFILE_MAIN_PUMP_MAX_DURATION_MS = 10000;
constexpr unsigned long PROFILE_NUTRIENT_PUMP_MAX_DURATION_MS = 5000;
#else
#error "Unknown HYDROPONIC_BUILD_PROFILE"
#endif

#endif
