#ifndef BUILD_PROFILE_H
#define BUILD_PROFILE_H

#define HYDROPONIC_PROFILE_OPERATIONAL 0
#define HYDROPONIC_PROFILE_USB_STAGE1 1

#ifndef HYDROPONIC_BUILD_PROFILE
#define HYDROPONIC_BUILD_PROFILE HYDROPONIC_PROFILE_OPERATIONAL
#endif

#if HYDROPONIC_BUILD_PROFILE == HYDROPONIC_PROFILE_USB_STAGE1
#define HYDROPONIC_BUILD_PROFILE_NAME "USB_STAGE1"
constexpr bool ACTUATORS_LOCKED = true;
constexpr bool MQTT_PUMP_COMMANDS_ENABLED = false;
#elif HYDROPONIC_BUILD_PROFILE == HYDROPONIC_PROFILE_OPERATIONAL
#define HYDROPONIC_BUILD_PROFILE_NAME "OPERATIONAL"
constexpr bool ACTUATORS_LOCKED = false;
constexpr bool MQTT_PUMP_COMMANDS_ENABLED = true;
#else
#error "Unknown HYDROPONIC_BUILD_PROFILE"
#endif

#endif
